import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { PeerService, PEER_PREFIX } from '../dist/services/peer-service.js';
const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'remoteagent-peer-'));
let now = Date.now();
const clock = () => now;
const yes = async () => true;
try {
  const a = new PeerService(dir, '100001', clock);
  const b = new PeerService(dir, '100002', clock);
  const invite = b.invite('receiver_bot', 'session-uuid', '111');
  a.add('target', invite, '222');
  assert.equal(a.list().links[0].verifiedAt, undefined);
  assert.throws(() => a.add('target', invite, '222'));
  const probe = a.probe('target');
  assert.equal(probe.target, '@receiver_bot');
  assert.throws(() => a.probe('target'), /60 seconds/);
  assert.equal(await b.receive('100001', probe.text, async () => false), undefined);
  assert.equal(await b.receive('100001', PEER_PREFIX + '{', yes), undefined);
  assert.equal(await b.receive('100001', '/start', yes), undefined);
  const forged = JSON.parse(probe.text.slice(PEER_PREFIX.length)); forged.token = 'bad';
  assert.equal(await b.receive('100001', PEER_PREFIX + JSON.stringify(forged), yes), undefined);
  const ack = await b.receive('100001', probe.text, yes);
  assert.equal(ack.target, '100001');
  assert.equal(await b.receive('100001', probe.text, yes), undefined, 'Duplicate must not generate another reply');
  assert.equal(await b.receive('100003', probe.text, yes), undefined, 'Consumed invitation cannot register another sender');
  assert.equal(await a.receive('100003', ack.text, yes), undefined, 'Verify actual Telegram sender, not username');
  const restarted = new PeerService(dir, '100001', clock);
  assert.ok((await restarted.receive('100002', ack.text, yes)).notice);
  assert.equal(await restarted.receive('100002', ack.text, yes), undefined);
  assert.equal(restarted.list().links[0].verifiedAt, now);
  assert.equal((await fs.stat(path.join(dir, 'peers/100001.json'))).mode & 0o777, 0o600);
  assert.ok(!(await fs.readFile(path.join(dir, 'peers/100001.json'), 'utf8')).includes(JSON.parse(Buffer.from(invite, 'base64url')).token));
  now += 60_001;
  const again = restarted.probe('target');
  assert.ok((await b.receive('100001', again.text, yes)).text, 'Recheck works without retaining invitation token');
  b.remove(b.list().incoming[0].id);
  now += 60_001;
  assert.equal(await b.receive('100001', restarted.probe('target').text, yes), undefined, 'Revoked grant is rejected');
  const expiring = b.invite('receiver_bot', 'session-uuid', '111');
  a.add('expiry', expiring, '222');
  now += 31 * 60_000;
  assert.throws(() => a.probe('expiry'), /expired/);
  assert.throws(() => a.add('expired', expiring, '222'), /expired/);
  const race = b.invite('receiver_bot', 'session-uuid', '111'); a.add('race', race, '222');
  const raceProbe = a.probe('race');
  assert.equal(await b.receive('100001', raceProbe.text, async () => { b.remove(JSON.parse(Buffer.from(race, 'base64url')).id); return true; }), undefined);
  console.log('PASS peer: two-party roundtrip, sender ID, no execution, duplicate/forgery/expiry rejection, restart, revoke race, recheck and secret disposal');
} finally { await fs.rm(dir, { recursive: true, force: true }); }
